"""
Data models and MongoDB-compatible document schemas for LAUNCH//REVERSE.
Distinguishes epistemological status: OBSERVED, INFERRED, HYPOTHESIS, SIMULATED.
"""

from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field


class LaunchArtifact(BaseModel):
    """
    Structured representation of a public launch artifact.
    Designed for MongoDB document storage and Pandas DataFrame analysis.
    """
    id: str = Field(..., description="Unique artifact identifier")
    case_study_id: str = Field(..., description="Case study slug (e.g. wispr-flow, gamma, example-ai)")
    date: str = Field(..., description="Date of publication (YYYY-MM-DD)")
    day_offset: int = Field(..., description="Days relative to launch (e.g. -7, 0, +2)")
    day_label: str = Field(..., description="Display label (e.g. 'DAY -7')")
    platform: str = Field(..., description="X, ProductHunt, LinkedIn, YouTube, Substack")
    author: str = Field(..., description="Author handle or name")
    author_type: str = Field(..., description="Founder, Core Team, Creator, Tech Influencer, Early Adopter")
    company: str = Field(..., description="Company name")
    content_type: str = Field(..., description="Text + Video, Contrarian Thread, Benchmark Graphic, Launch Post, Teaser Poll")
    hook_type: str = Field(..., description="Contrarian, Velocity Proof, Pain-point Relatability, Curiosity Gap, Mechanism Reveal")
    narrative: str = Field(..., description="Primary narrative theme")
    cta: str = Field(..., description="Waitlist, Free Tier, Chrome Extension, Open Source, Follow")
    launch_phase: str = Field(..., description="Pre-launch, Teaser, Launch Day, Post-launch Amplification, Proof & Defense")
    engagement_views: int = Field(0, description="Estimated public view impressions")
    engagement_interactions: int = Field(0, description="Likes, reposts, comments, upvotes")
    source_type: str = Field("SIMULATED", description="SIMULATED or PUBLIC-ARTIFACT CONCEPT")
    epistemic_status: str = Field("OBSERVED", description="OBSERVED, INFERRED, HYPOTHESIS, or SIMULATED")
    raw_content: str = Field(..., description="Verbatim public text or excerpt")
    structured_extracted_entities: List[str] = Field(default_factory=list, description="Extracted keywords, products, people")
    confidence_score: float = Field(0.9, description="Extraction confidence score (0.0 - 1.0)")


class LaunchDnaProfile(BaseModel):
    """
    Illustrative 8-dimensional classification for a launch strategy.
    Note: Demonstrates analytical framework, not measured causal effects.
    """
    case_study_id: str
    company_name: str
    curiosity: int = Field(..., ge=0, le=100)
    narrative_tension: int = Field(..., ge=0, le=100)
    founder_involvement: int = Field(..., ge=0, le=100)
    creator_involvement: int = Field(..., ge=0, le=100)
    product_proof: int = Field(..., ge=0, le=100)
    visual_content: int = Field(..., ge=0, le=100)
    social_proof: int = Field(..., ge=0, le=100)
    contrarian_framing: int = Field(..., ge=0, le=100)
    summary_archetype: str
    qualitative_notes: str


class HypothesisRecord(BaseModel):
    """
    Evidence-grounded hypothesis generated by Pattern Hunter and challenged by Skeptic.
    """
    id: str
    title: str
    observation: str
    supporting_artifacts_count: int
    supporting_launch_sequences: int
    supporting_author_types: int
    hypothesis_mechanism: str
    counterevidence: str
    counterevidence_exceptions_count: int
    assumptions: List[str]
    skeptic_critique: str
    confidence_level: str  # LOW, MEDIUM, HIGH
    status: str  # Needs more data, Plausible but unverified, Contradicted
    next_data_required: str
    tags: List[str]
